#ifndef ATL_SKILLS_H
#define ATL_SKILLS_H

typedef enum {
    SK_MINING,
    SK_LUMBERJACK,
    SK_QUARRYING,
    SK_HORSE_TRAINING,
    SK_WEAPONSMITH,
    SK_ARMORER,
    SK_BUILDING,
    SK_SHIPBUILDING,
    SK_ENTERTAINMENT,
    SK_STEALTH,
    SK_OBSERVATION,
    SK_TACTICS,
    SK_RIDING,
    SK_SWORD,
    SK_CROSSBOW,
    SK_LONGBOW,
    SK_MAGIC,
    MAXSKILLS
} skill_t;


#endif
