#!/bin/bash
. test_framework.inc

if [ -z $1 ] || [ ! -x $1 ] ; then
  echo "usage: $0 <executable>"
  exit 1
fi

FILES="orders maillist send summary data/0 data/1"
DIRECTORIES="reports nreports data"
function fail {
  rm -rf $FILES $DIRECTORIES
  exit $1
}

touch orders
( echo P ; echo orders ) | $1
let RESULT=$?
if [ $RESULT -ne 0 ] ; then
  echo "non-zero exit code from server: $RESULT"
  fail $RESULT
fi
assert_files $FILES || fail $?
assert_directories $DIRECTORIES || fail $?
fail 0

