#!/bin/bash
. test_framework.inc

if [ -z $1 ] || [ ! -x $1 ] ; then
  echo "usage: $0 <executable>"
  exit 1
fi
(echo W ; echo Q ) | $1
RESULT=$?

FILES="summary data/0"
DIRECTORIES="data"
function fail {
  rm -rf $FILES $DIRECTORIES
  exit $1
}
assert_files $FILES || fail $?
assert_directories $DIRECTORIES || fail $?
fail $RESULT
