#ifndef ATL_ITEMS_H
#define ATL_ITEMS_H

typedef enum {
    I_IRON,
    I_WOOD,
    I_STONE,
    I_HORSE,
    I_SWORD,
    I_CROSSBOW,
    I_LONGBOW,
    I_CHAIN_MAIL,
    I_PLATE_ARMOR,
    I_AMULET_OF_DARKNESS,
    I_AMULET_OF_DEATH,
    I_AMULET_OF_HEALING,
    I_AMULET_OF_TRUE_SEEING,
    I_CLOAK_OF_INVULNERABILITY,
    I_RING_OF_INVISIBILITY,
    I_RING_OF_POWER,
    I_RUNESWORD,
    I_SHIELDSTONE,
    I_STAFF_OF_FIRE,
    I_STAFF_OF_LIGHTNING,
    I_WAND_OF_TELEPORTATION,
    MAXITEMS
} item_t;

#endif
