#ifndef ATL_SPELLS_H
#define ATL_SPELLS_H

typedef enum {
    SP_BLACK_WIND,
    SP_CAUSE_FEAR,
    SP_CONTAMINATE_WATER,
    SP_DAZZLING_LIGHT,
    SP_FIREBALL,
    SP_HAND_OF_DEATH,
    SP_HEAL,
    SP_INSPIRE_COURAGE,
    SP_LIGHTNING_BOLT,
    SP_MAKE_AMULET_OF_DARKNESS,
    SP_MAKE_AMULET_OF_DEATH,
    SP_MAKE_AMULET_OF_HEALING,
    SP_MAKE_AMULET_OF_TRUE_SEEING,
    SP_MAKE_CLOAK_OF_INVULNERABILITY,
    SP_MAKE_RING_OF_INVISIBILITY,
    SP_MAKE_RING_OF_POWER,
    SP_MAKE_RUNESWORD,
    SP_MAKE_SHIELDSTONE,
    SP_MAKE_STAFF_OF_FIRE,
    SP_MAKE_STAFF_OF_LIGHTNING,
    SP_MAKE_WAND_OF_TELEPORTATION,
    SP_SHIELD,
    SP_SUNFIRE,
    SP_TELEPORT,
    MAXSPELLS
} spell_t;

extern int spelllevel[];
extern const char *spelldata[];

#endif
