#!/bin/sh

pwd=$PWD
while [ ! -d .git ] ; do
  if [ "$PWD"="/" ] ; then
    echo "$0 must be run from inside the repository"
    cd $pwd
    exit 1
  fi
  cd ..
done

cd build && make test && lua ../lua/tests.lua
